Repository manujosephv/pytorch_tabular, pull requests merged in 2024-12, with the labels that each got.

#517 Enable Support for Multi-GPU Training
  src/pytorch_tabular/categorical_encoders.py
  src/pytorch_tabular/config/config.py
  src/pytorch_tabular/feature_extractor.py
  src/pytorch_tabular/models/base_model.py
  src/pytorch_tabular/ssl_models/base_model.py
  src/pytorch_tabular/ssl_models/dae/dae.py
  src/pytorch_tabular/tabular_datamodule.py
  src/pytorch_tabular/tabular_model.py
Labels: enhancement, size:M

#520 Add Built-in Support for Model Stacking
  docs/apidocs_model.md
  docs/imgs/model_stacking_concept.png
  docs/models.md
  docs/tutorials/16-Model Stacking.ipynb
  mkdocs.yml
  src/pytorch_tabular/models/__init__.py
  src/pytorch_tabular/models/stacking/__init__.py
  src/pytorch_tabular/models/stacking/config.py
  src/pytorch_tabular/models/stacking/stacking_model.py
  src/pytorch_tabular/models/tabnet/config.py
  tests/test_model_stacking.py
Labels: enhancement, size:L

#524 chore(ci): setting concurrency
  .github/workflows/testing.yml
Labels: size:XS
